USE [master]
GO

CREATE DATABASE [Futbol]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Futbol', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Futbol.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Futbol_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Futbol_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Futbol].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Futbol] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Futbol] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Futbol] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Futbol] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Futbol] SET ARITHABORT OFF 
GO

ALTER DATABASE [Futbol] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Futbol] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Futbol] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Futbol] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Futbol] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Futbol] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Futbol] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Futbol] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Futbol] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Futbol] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Futbol] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Futbol] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Futbol] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Futbol] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Futbol] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Futbol] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Futbol] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Futbol] SET RECOVERY FULL 
GO

ALTER DATABASE [Futbol] SET  MULTI_USER 
GO

ALTER DATABASE [Futbol] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Futbol] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Futbol] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Futbol] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Futbol] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Futbol] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Futbol] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Futbol] SET  READ_WRITE 
GO

