USE [Futbol]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Hakem](
	[hakemID] [int] IDENTITY(1,1) NOT NULL,
	[hakemAdi] [nvarchar](50) NULL,
	[hakemSoyadi] [nvarchar](50) NULL,
 CONSTRAINT [PK_Hakem] PRIMARY KEY CLUSTERED 
(
	[hakemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

