USE [Futbol]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Mac](
	[macID] [int] IDENTITY(1,1) NOT NULL,
	[hakemID] [int] NULL,
	[takimID] [int] NULL,
	[stadID] [int] NULL,
	[tarih] [date] NULL,
	[macAdi] [nvarchar](50) NULL,
 CONSTRAINT [PK_Mac] PRIMARY KEY CLUSTERED 
(
	[macID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Mac]  WITH CHECK ADD  CONSTRAINT [FK_Mac_Hakem] FOREIGN KEY([hakemID])
REFERENCES [dbo].[Hakem] ([hakemID])
GO

ALTER TABLE [dbo].[Mac] CHECK CONSTRAINT [FK_Mac_Hakem]
GO

ALTER TABLE [dbo].[Mac]  WITH CHECK ADD  CONSTRAINT [FK_Mac_Stad] FOREIGN KEY([stadID])
REFERENCES [dbo].[Stad] ([stadID])
GO

ALTER TABLE [dbo].[Mac] CHECK CONSTRAINT [FK_Mac_Stad]
GO

ALTER TABLE [dbo].[Mac]  WITH CHECK ADD  CONSTRAINT [FK_Mac_Takim] FOREIGN KEY([takimID])
REFERENCES [dbo].[Takim] ([takimID])
GO

ALTER TABLE [dbo].[Mac] CHECK CONSTRAINT [FK_Mac_Takim]
GO

