USE [Futbol]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Stad](
	[stadID] [int] NOT NULL,
	[stadAdi] [nvarchar](50) NULL,
	[kurulusYili] [date] NULL,
 CONSTRAINT [PK_Stad] PRIMARY KEY CLUSTERED 
(
	[stadID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

